In [13]:
import sys
import numpy as np

def cipher_encryption(plain, key):
    # Handle condition if the message is odd.
    # Enter code here>
    plain = plain.upper().replace(" ", "")
    # Make sure the last letter is not X
    if len(plain) % 2 == 1:
        if plain[len(plain) - 1] != 'X':
            plain += 'X'
        else:
            plain = plain[:-1]
    
    # Convert msg to matrices
    key = "hill"
    key = key.upper()
    msg2d = np.zeros((2,len(plain)//2), dtype=int)
    for i in range(len(plain)):
        msg2d[i%2, i//2] = ord(plain[i]) - ord('A')

    print("This is your message visualized: \n" + str(msg2d))

    # Convert key to 2x2
    key2d = np.zeros((2,2), dtype=int)
    for i in range(4):
        key2d[i//2, i%2] = ord(key[i]) - ord('A')

    print("This is your key visualized: \n" + str(key2d))

    # checking validity of the key
    det = key2d[0][0]*key2d[1][1] - key2d[0][1]*key2d[1][0]
    det %= 26
    detInv = -1
    for i in range(26):
        tempInv = det*i
        if (tempInv)%26 == 1:
            detInv = i
            break
    if detInv == -1:
        return "Error: Invalid key"
    keyInv = np.zeros((2,2), dtype=int)
    # Was not able to find an easier way
    # Hence, did inverse without a loop
    keyInv[0][0] = key2d[1][1]
    keyInv[0][1] = -key2d[0][1]
    keyInv[1][0] = -key2d[1][0]
    keyInv[1][1] = key2d[0][0]
    keyInv *= detInv
    keyInv = np.mod(keyInv, 26)

    # This will encrypt the text.
    encryp_text = ""
    for i in range(msg2d.shape[1]):
        temp = np.dot(key2d, msg2d[:,i])
        temp %= 26
        encryp_text += chr(temp[0]+ord('A')) + chr(temp[1]+ord('A'))
    
    print("Encrypted text: {}".format(encryp_text))
    return encryp_text

In [14]:
def cipher_decryption(cipher, key):
    # Convert cipher to matrices
    cipher = [ord(i) - 65 for i in cipher]

    # .T will transpose the array
    # Transpose = swap rows and columns
    cipher_mat = np.array(cipher).reshape(-1, 2).T

    # Convert key to 2x2
    key = [ord(i) - 65 for i in key]
    key_mat = np.array(key).reshape(2, 2)

    # Finding determinant of key
    det = int(np.linalg.det(key_mat))

    # Finding multiplicative inverse of determinant
    # using a brute force method
    mul_inv = 0
    for i in range(26):
        temp_inv = det * i
        if temp_inv % 26 == 1:
            mul_inv = i
            break

    # Finding adjoint of key
    adj_key_mat = np.zeros((2, 2), dtype=int)
    adj_key_mat[0][0] = key_mat[1][1]
    adj_key_mat[1][1] = key_mat[0][0]
    adj_key_mat[0][1] = -key_mat[0][1]
    adj_key_mat[1][0] = -key_mat[1][0]

    # Applying decryption formula
    # .dot does the dot product, maxtrix
    # multiplication.
    plain_mat = mul_inv * adj_key_mat.dot(cipher_mat)

    # Convert the matrix to plain text
    plain = ""
    for i in plain_mat.T.flatten():
        plain += chr(i % 26 + 65)

    # If padding was added, remove it.
    if plain[-1] == 'X':
        plain = plain[:-1]
        
    return plain


In [15]:
def main():
    # First run
    plaintext = "Secret Message"
    plaintext = plaintext.upper().replace(" ","")
    key = "hill"
    key = key.upper().replace(" ","")
    
    # Encryption
    ciphertext = cipher_encryption(plaintext, key)
    
    # Decryption
    decrypted_text = cipher_decryption(ciphertext, key)

    print("Decrypted text: {}".format(decrypted_text))

    # Second run (Asks the user)
    plaintext = input(str("Enter custom message: "))
    print("Your message: " +    plaintext)
    key = "hill"
    key = key.upper().replace(" ","")
    ciphertext = cipher_encryption(plaintext, key)
    decrypted_text = cipher_decryption(ciphertext, key)
    print("Decrypted text: {}".format(decrypted_text))

if __name__ == '__main__':
    main()


This is your message visualized: 
[[18  2  4 12 18  0  4]
 [ 4 17 19  4 18  6 23]]
This is your key visualized: 
[[ 7  8]
 [11 11]]
Encrypted text: CIUBYTMUKGWOEL
Decrypted text: SECRETMESSAGE
Your message: Heena Rathore
This is your message visualized: 
[[ 7  4  0  0  7 17]
 [ 4 13 17 19 14  4]]
This is your key visualized: 
[[ 7  8]
 [11 11]]
Encrypted text: DRCFGFWBFXVX
Decrypted text: HEENARATHORE
